---
title: "Les métiers de la donnée dans l'enseignement supérieur et la recherche"
subtitle: "Analyse des données d'enquête"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
    rmarkdown::html_document:
      #number_sections: true
      theme: paper
      toc: true
      toc_depth: 4
      collapsed: true
      smooth_scroll: true
      css: styles.css
      includes:
        in_header: header.html
        after_body: footer.html
---

```{r setup, include=FALSE}
# Settings summarytools
library(summarytools)
st_options(plain.ascii = FALSE,               # This is very handy in all Rmd documents
           style = "rmarkdown",               # This too
           footnote = NA,                    # Avoids footnotes which would clutter the results
           subtitle.emphasis = FALSE
         # This is a setting to experiment with - according to the theme used, it might improve the headings layout
)

# Paramètres généraux
knitr::opts_chunk$set(
	eval = TRUE,
	echo = FALSE,
	fig.align = "center",
	fig.show = "hold",
	message = FALSE,
	warning = FALSE,
	collapse = TRUE,
	out.width = "100%",
	results = "asis"
)
```

```{r logo}
# Logo Datactivist haut de page
htmltools::img(src = "https://nextcloud.datactivist.coop/s/o53wzfMNnFosQni/preview", 
               alt = 'logo', 
               style = 'position:absolute; top:0; left:0.5; padding-top:10px;') #padding=taille des espaces autour
```

```{r data}
# Librairies
library(tidyverse)
library(ggwordcloud)
library(gt)
library(gtExtras)
library(htmltools)
library(grid)
library(gridExtra)

# Données
data <- read_csv("../data/donnees_lemmatisees_cols_Autre2.csv") |> 
    filter(!is.na(`Date de soumission`)) # réponses complètes donc fiables
data_clean_names <- data |> 
    janitor::clean_names()
questions <- as.data.frame(colnames(data)) |> 
    rename(rowname = `colnames(data)`)
```

# Données issues du questionnaire

## Analyse de chaque question individuellement 

### Statistiques générales

```{r}
data_summary <- data |> select(-1)

print(dfSummary(data_summary, style = "grid", graph.magnif = 1, 
                valid.col = FALSE, varnumbers = FALSE, tmp.img.dir = "/tmp", 
                max.distinct.values = 5, headings = TRUE, method = "render", 
                col.widths  = c(300, 200, 100, 50, 20)),
      max.tbl.height = 600,
      method = "render")
``` 

### Statistiques par question


```{r fonctions graphs}
donut_plot <- function(data, variable, titre){
    data |> 
        group_by({{variable}}) |> summarise(Freq = n()) |> 
        mutate(fraction = Freq / sum(Freq),
               proportion = round((Freq / sum(Freq))*100),
               ymax = cumsum(fraction),
               ymin = c(0, head(ymax, n=-1)), 
               labelPosition = (ymax + ymin) / 2) |> 
        ggplot(aes(ymax = ymax, ymin = ymin, xmax = 3.3, xmin = 2, fill = {{variable}})) +
          geom_rect(col = "white", size = 2) +
          geom_text(x=4, aes(y=labelPosition, label = paste(proportion,"%",sep = "")), color = "#333333", size=7) +
          geom_text(aes(x = 0, y = 0, label = sum(Freq)), col = "#333333", alpha=0.8, size=14, fontface="bold", inherit.aes = FALSE) +
          scale_fill_manual(values = c('#ffe725','#5770BE', "#169B62", "#666666")) +
          coord_polar(theta="y") +
          labs(title = titre,
               subtitle = paste0(data |> filter(!is.na({{variable}})) |> nrow(), " réponses, soit ", 
                                round(((data |> filter(!is.na({{variable}})) |> nrow()) / nrow(data)) * 100, 0), "% des répondants")) +
          xlim(c(0, 4)) +   
          theme_void() +
          theme(legend.position = "right",
                text = element_text(family = "Monsterrat", size = 12),
                plot.title = element_text(face = "bold"),
                plot.background = element_rect(fill = "white", colour="white"),
                panel.background = element_rect(fill = "white", colour = "white"),
                legend.background = element_rect(fill = "white", colour = "white"))+
          guides(fill = guide_legend(title = ""))
} 
barplot_qs_multiples <- function(data, min, max, slice_min, slice_max, color, titre){
    table <- data |> 
        select(min:max)|> mutate_all(na_if, "Non") |> 
        summarise_all(funs(sum(!is.na(.)))) |> 
        t()|> as.data.frame() |> 
        rownames_to_column() |> 
        mutate(percent = round((V1 / sum(V1))*100, 0),
               rowname = str_extract(rowname, "(?<=\\[).*"),
               rowname = substr(rowname, 1, nchar(rowname)-1),
               rowname = str_extract(rowname, "^[^(]+")) |> 
        select(rowname, V1, percent) |> ungroup() |> 
        arrange(desc(percent)) |> slice(slice_min:slice_max) |> 
        mutate(rowname = fct_reorder(rowname, V1))
    table |> 
        ggplot(aes(x = rowname, y = V1)) +
          geom_bar(stat = "identity", width = .6, fill = color) +
          coord_flip() +
          labs(x = "", y = "Nombre de réponses", title = titre,
               subtitle = paste(sum(table$V1), "réponses")) +
          scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 40)) + 
          theme_classic() +
          theme(legend.position = "none",
                text = element_text(family = "Monsterrat", size = 12),
                plot.title = element_text(face = "bold", hjust = ifelse(nchar(titre) > 40, 1, 0)),
                axis.title.y = element_blank(),
                axis.line.x = element_blank(),
                axis.line.y = element_blank(),
                axis.ticks.y = element_blank(),
                axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
          geom_text(aes(y = V1 + 0.05*max(V1), x = rowname, label = paste(percent, "%", sep = "")), 
                    color = "#333333", size = 3, check_overlap = T)
}
wordcloud_autre <- function(data, variable, titre, n_slice, n_max_size){
    table <- data |> select({{variable}}) |> 
        group_by({{variable}}) |> 
        mutate(n=n()) |> na.omit() |> distinct() |> 
        rename(col = 1) |> ungroup() |> 
        arrange(desc(n)) |> slice(1:n_slice)
    table |> ggplot(aes(label = col, size = n)) +
          geom_text_wordcloud(color = rep_len(c('#ffe725','#5770BE', "#169B62"), nrow(table)), family = "Montserrat") +
          scale_size_area(max_size = n_max_size) +
          labs(title = paste0("\n", titre),
               subtitle = paste0(data |> filter(!is.na({{variable}})) |> nrow(), " réponses, soit ", 
                                round(((data |> filter(!is.na({{variable}})) |> nrow()) / nrow(data)) * 100, 0), "% des répondants")) +
          theme_minimal() +
          theme(plot.title = element_text(face = "bold", size = 15),
                plot.subtitle = element_text(margin = margin(t = 0, r = 0, b = -60, l = 0)))
}
barplot_qs_unique <- function(data, variable, titre){
    data |> 
        filter({{variable}} != "Autre", 
               !is.na({{variable}})) |> 
        group_by({{variable}}) |> 
        summarise(n = n()) |> rename(col = 1) |> 
        mutate(col = fct_reorder(col, n),
               percent = round((n / sum(n))*100, 0)) |> 
        ggplot(aes(x = col, y = n)) +
          geom_bar(stat = "identity", width = .6, fill = "#5770BE") +
          coord_flip() +
          labs(x = "", y = "Nombre de répondants", title = titre,
               subtitle = paste0(data |> filter(!is.na({{variable}})) |> nrow(), " réponses, soit ", 
                                round(((data |> filter(!is.na({{variable}})) |> nrow()) / nrow(data)) * 100, 0), "% des répondants")) +
          scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 40)) + 
          theme_classic() +
          theme(legend.position = "none",
                text = element_text(family = "Monsterrat", size = 12),
                plot.title = element_text(face = "bold", hjust = ifelse(nchar(titre) > 40, 1, 0)),
                axis.title.y = element_blank(),
                axis.line.x = element_blank(),
                axis.line.y = element_blank(),
                axis.ticks.y = element_blank(),
                axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
          geom_text(aes(y = n + 0.05*max(n), x = col, label = paste(percent, "%", sep = "")), 
                    color = "#333333", size = 3, check_overlap = T)
}
barplot_qs_unique_top_n <- function(data, variable, slice_min, slice_max, titre){
    table <- data |> 
        filter({{variable}} != "Autre", 
               !is.na({{variable}})) |> 
        group_by({{variable}}) |> 
        summarise(n = n()) |> rename(col = 1) |> 
        mutate(col = fct_reorder(col, n),
               percent = round((n / sum(n))*100, 0)) |> 
        arrange(desc(n)) |> 
        slice(slice_min:slice_max) 
    table |> 
        ggplot(aes(x = col, y = n)) +
          geom_bar(stat = "identity", width = .6, fill = "#5770BE") +
          coord_flip() +
          labs(x = "", y = "Nombre de répondants", title = titre,
               subtitle = paste0(data |> filter(!is.na({{variable}})) |> nrow(), " réponses, soit ", 
                                round(((data |> filter(!is.na({{variable}})) |> nrow()) / nrow(data)) * 100, 0), "% des répondants")) +
          scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 40)) + 
          #scale_y_discrete(limits = 1:max(table$n)) +
          theme_classic() +
          theme(legend.position = "none",
                text = element_text(family = "Monsterrat", size = 12),
                plot.title = element_text(face = "bold", hjust = ifelse(nchar(titre) > 40, 1, 0)),
                axis.title.y = element_blank(),
                axis.line.x = element_blank(),
                axis.line.y = element_blank(),
                axis.ticks.y = element_blank(),
                axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
          geom_text(aes(y = n + 0.05*max(n), x = col, label = paste(percent, "%", sep = "")), 
                    color = "#333333", size = 3, check_overlap = T)
}
```

```{r out.width='60%'}
data |> 
    mutate(`Langue de départ` = case_when(`Langue de départ` == "fr" ~ "français",
                                          `Langue de départ` == "en" ~ "anglais")) |> 
    donut_plot(`Langue de départ`, "Langue de départ")

data |> 
    filter(!is.na(`Dans quel type d'établissement exercez-vous votre activité ?`)) |> 
    mutate(`Dans quel type d'établissement exercez-vous votre activité ?` = factor(`Dans quel type d'établissement exercez-vous votre activité ?`, ordered = TRUE, levels = c("Ecole", "Organisme de recherche", "Université", "Autre"))) |> 
    donut_plot(`Dans quel type d'établissement exercez-vous votre activité ?`, "Dans quel type d'établissement exercez-vous votre activité ?")

wordcloud_autre(data, `Dans quel type d'établissement exercez-vous votre activité ? [Autre]`, "Dans quel type d'établissement exercez-vous votre activité ? [Autre]", 40, 10)

barplot_qs_multiples(data, 8, 12, 1, 11, "#5770BE", "Où réalisez-vous votre activité en lien avec les données de \nrecherche ?")  

barplot_qs_unique(data, `Sur quel domaine thématique réalisez-vous votre activité sur les données ?`, "Sur quel domaine thématique réalisez-vous votre activité sur \nles données ?")  

barplot_qs_multiples(data, 16, 22, 1, 11, "#5770BE", "Sur quelle(s) partie(s) du cycle de vie des données intervenez-vous ?")
```

```{r fig.width=12}
plot_plus <- barplot_qs_multiples(data, 23, 37, 1, 10, "#169B62", "") +
    labs(caption = "Top 10 des catégories les plus représentées") +
    theme(plot.caption = element_text(face = "italic"))
plot_moins <- barplot_qs_multiples(data, 23, 37, 11, 15, "#ffe725", "") +
    labs(caption = "Top 5 des catégories les moins représentées") +
    theme(plot.caption = element_text(face = "italic"))
grid.arrange(plot_plus, plot_moins, ncol = 2, top = textGrob("Quelles sont les activités qu'implique votre travail sur les données ?",gp=gpar(fontsize = 15, font = 2)))

plot_plus <- barplot_qs_multiples(data, 38, 50, 1, 10, "#169B62", "") +
    labs(caption = "Top 10 des catégories les plus représentées") +
    theme(plot.caption = element_text(face = "italic"))
plot_moins <- barplot_qs_multiples(data, 38, 50, 11, 13, "#ffe725", "") +
    labs(caption = "Top 3 des catégories les moins représentées") +
    theme(plot.caption = element_text(face = "italic"))
grid.arrange(plot_plus, plot_moins, ncol = 2, top = textGrob("Comment intervenez-vous sur ces activités ?", gp = gpar(fontsize = 15, font = 2)))

plot_plus <- barplot_qs_multiples(data, 51, 65, 1, 10, "#169B62", "") +
    labs(caption = "Top 10 des catégories les plus représentées") +
    theme(plot.caption = element_text(face = "italic"))
plot_moins <- barplot_qs_multiples(data, 51, 65, 11, 15, "#ffe725", "") +
    labs(caption = "Top 5 des catégories les moins représentées") +
    theme(plot.caption = element_text(face = "italic"))
grid.arrange(plot_plus, plot_moins, ncol = 2, top = textGrob("Quel est le poids de chaque activité dans votre travail ?",gp=gpar(fontsize = 15, font = 2)))
```

```{r out.width='60%'}

barplot_qs_multiples(data, 66, 76, 1, 11, "#5770BE", "Sur quels types de données travaillez-vous ?")

wordcloud_autre(data, `Sur quels types de données travaillez-vous ? [Autre]`, "Sur quels types de données travaillez-vous ? [Autre]", 40, 12)

barplot_qs_unique(data, `Quel est votre niveau de diplôme ?`, "Quel est votre niveau de diplôme ?")  

data |> 
    mutate(nv_diplome = case_when(`Quel est votre niveau de diplôme ? [Autre]` == "Ph.D. (Québec)" ~ "PhD", 
                                  `Quel est votre niveau de diplôme ? [Autre]` == "PhD (USA)" ~ "PhD", 
                                  `Quel est votre niveau de diplôme ? [Autre]` == "Médicin + MSc biostatistic + MSc data science + PhD" ~ "PhD", 
                                  TRUE ~ `Quel est votre niveau de diplôme ? [Autre]`)) |> 
    wordcloud_autre(nv_diplome, "Quel est votre niveau de diplôme ? [Autre]", 40, 30)

barplot_qs_unique(data, `Quel est le domaine de votre formation initiale ?`, "Quel est le domaine de votre formation initiale ?")  

wordcloud_autre(data, `Quel est le domaine de votre formation initiale ? [Autre]`, "Quel est le domaine de votre formation initiale ? [Autre]", 40, 10)

barplot_qs_multiples(data, 81, 84, 1, 11, "#5770BE", "Vous êtes-vous formé à la gestion et la diffusion des \ndonnées de recherche ?")

barplot_qs_unique_top_n(data, `Quels postes, fonctions ou responsabilités significatifs avez-vous occupés dans l'enseignement supérieur et/ou la recherche, du plus récent au plus ancien ? [Intitulé du poste le plus récent]`, 1, 10, "Quels postes, fonctions ou responsabilités significatifs avez-vous \noccupés dans l'enseignement supérieur et/ou la recherche, \ndu plus récent au plus ancien ?") +
    labs(subtitle = "Top 10 des plus récents (t)")

barplot_qs_unique_top_n(data, `Quels postes, fonctions ou responsabilités significatifs avez-vous occupés dans l'enseignement supérieur et/ou la recherche, du plus récent au plus ancien ? [Intitulé du poste précédent]`, 1, 10, "Quels postes, fonctions ou responsabilités significatifs avez-vous \noccupés dans l'enseignement supérieur et/ou la recherche, \ndu plus récent au plus ancien ?") +
    labs(subtitle = "Top 10 des postes précédents (t-1)")

barplot_qs_unique_top_n(data, `Quels postes, fonctions ou responsabilités significatifs avez-vous occupés dans l'enseignement supérieur et/ou la recherche, du plus récent au plus ancien ? [Intitulé du poste précédent] 2`, 1, 10, "Quels postes, fonctions ou responsabilités significatifs avez-vous \noccupés dans l'enseignement supérieur et/ou la recherche, \ndu plus récent au plus ancien ?") +
    labs(subtitle = "Top 10 des postes précédents (t-2)")

barplot_qs_unique_top_n(data, `Quels postes, fonctions ou responsabilités significatifs avez-vous occupés dans l'enseignement supérieur et/ou la recherche, du plus récent au plus ancien ? [Intitulé du poste précédent] 3`, 1, 10, "Quels postes, fonctions ou responsabilités significatifs avez-vous \noccupés dans l'enseignement supérieur et/ou la recherche, \ndu plus récent au plus ancien ?") +
    labs(subtitle = "Top 10 des postes précédents (t-3)")

barplot_qs_unique_top_n(data, `Quels postes, fonctions ou responsabilités significatifs avez-vous occupés dans l'enseignement supérieur et/ou la recherche, du plus récent au plus ancien ? [Intitulé du poste précédent] 4`, 1, 10, "Quels postes, fonctions ou responsabilités significatifs avez-vous \noccupés dans l'enseignement supérieur et/ou la recherche, \ndu plus récent au plus ancien ?") +
    labs(subtitle = "Top 10 des postes précédents (t-4)")

data |> 
    filter(!is.na(`Quelle est votre catégorie d'emploi actuel ?`)) |> 
    mutate(`Quelle est votre catégorie d'emploi actuel ?` = str_extract(`Quelle est votre catégorie d'emploi actuel ?`, "^[^(]+")) |> 
    donut_plot(`Quelle est votre catégorie d'emploi actuel ?`, "Quelle est votre catégorie d'emploi actuel ?")

barplot_qs_unique(data, `Précisez votre catégorie`, "Emploi actuel")  

data |> 
    filter(!is.na(`Précisez votre catégorie 2`)) |> 
    donut_plot(`Précisez votre catégorie 2`, "Catégorie d'emploi actuel")

barplot_qs_unique(data, `Précisez votre branche d'activité.`, "Précisez votre branche d'activité.")  

wordcloud_autre(data, `Précisez votre branche d'activité. [Autre]`, "Précisez votre branche d'activité. [Autre]", 40, 10)

wordcloud_autre(data, `Dans le cadre de votre activité sur les données, sur quels réseaux ou communautés vous appuyez-vous ?`, "Dans le cadre de votre activité sur les données, \nsur quels réseaux ou communautés vous appuyez-vous ?", 40, 10)  
```

```{r fig.width=12}
plot_plus <- barplot_qs_multiples(data, 96, 110, 1, 10, "#169B62", "") +
    labs(caption = "Top 10 des catégories les plus représentées") +
    theme(plot.caption = element_text(face = "italic"))
plot_moins <- barplot_qs_multiples(data, 96, 110, 11, 15, "#ffe725", "") +
    labs(caption = "Top 5 des catégories les moins représentées") +
    theme(plot.caption = element_text(face = "italic"))
grid.arrange(plot_plus, plot_moins, ncol = 2, top = textGrob("Sur quelles activités auriez-vous besoin d'une formation ?", gp = gpar(fontsize = 15, font = 2)))
```

```{r out.width='60%'}
wordcloud_autre(data, `Sur quelles activités auriez-vous besoin d'une formation ? [Autre]`, "Sur quelles activités auriez-vous besoin d'une formation ? [Autre]", 10, 13)

wordcloud_autre(data, `Sous quel intitulé présentez-vous votre poste actuel ?`, "Sous quel intitulé présentez-vous votre poste actuel ?", 40, 10)

data |> 
    filter(!is.na(`Votre établissement/organisme a-t-il formalisé une organisation des activités ou des rôles sur les données à l'échelle de l'établissement ou de différentes structures ?`)) |> 
    donut_plot(`Votre établissement/organisme a-t-il formalisé une organisation des activités ou des rôles sur les données à l'échelle de l'établissement ou de différentes structures ?`, "Votre établissement/organisme a-t-il formalisé une \norganisation des activités ou des rôles sur les données \nà l'échelle de l'établissement ou de différentes structures ?")

data |> 
    mutate(consentement = case_when(is.na(`Accepteriez-vous un entretien pour approfondir cette enquête ?  Nous souhaitons approfondir cette enquête au travers d'entretiens avec des profils variés de professionnels des données de recherche.  Si vous êtes volontaire pour un entretien en visio dans les prochains mois, merci de laisser vos coordonnées pour que nous puissions vous recontacter.  [Prénom]`) ~ "Non",
                                    TRUE ~ "Oui")) |>
    group_by(consentement) |> summarise(Freq = n()) |> 
    mutate(fraction = Freq / sum(Freq),
           proportion = round((Freq / sum(Freq))*100),
           ymax = cumsum(fraction),
           ymin = c(0, head(ymax, n=-1)), 
           labelPosition = (ymax + ymin) / 2) |> 
    ggplot(aes(ymax = ymax, ymin = ymin, xmax = 3.3, xmin = 2, fill = consentement)) +
      geom_rect(col = "white", size = 2) +
      geom_text(x=4, aes(y=labelPosition, label = paste(proportion,"%",sep = "")), color = "#333333", size=7) +
      geom_text(aes(x = 0, y = 0, label = sum(Freq)), col = "#333333", alpha=0.8, size=14, fontface="bold", inherit.aes = FALSE) +
      scale_fill_manual(values = c('#ffe725','#5770BE', "#169B62")) +
      coord_polar(theta="y") +
      labs(title = "Accepteriez-vous un entretien pour approfondir cette \nenquête ?") +
      xlim(c(0, 4)) +   
      theme_void() +
      theme(legend.position = "right",
            text = element_text(family = "Monsterrat", size = 12),
            plot.title = element_text(face = "bold"),
            plot.background = element_rect(fill = "white", colour="white"),
            panel.background = element_rect(fill = "white", colour = "white"),
            legend.background = element_rect(fill = "white", colour = "white"))+
      guides(fill = guide_legend(title = ""))
```

```{r}
data |> 
    filter(!is.na(`Vous pouvez décrire ici les éléments relatifs à cette formalisation, fournir un lien ou indiquer toute autre information.`)) |> 
    select(`ID de la réponse`, `Vous pouvez décrire ici les éléments relatifs à cette formalisation, fournir un lien ou indiquer toute autre information.`) |> 
    sample_n(40) %>%
    rename(`Éléments de formalisation` = `Vous pouvez décrire ici les éléments relatifs à cette formalisation, fournir un lien ou indiquer toute autre information.`) |> 
      gt() %>%
      gt_theme_nytimes() %>%
      tab_header(title = "Vous pouvez décrire ici les éléments relatifs à cette formalisation, fournir un lien ou indiquer toute autre information.",
                 subtitle = "20 éléments de formalisation aléatoires") %>%
      # tab_style(
      #       style = list(cell_text(weight = "lighter")),
      #       locations = cells_body(
      #         columns = `Polarité`)) %>%
      tab_options(table.font.size = 17,
                      table.border.bottom.width = 1) %>%
      div(style='height:700px; overflow-y: scroll')
```


```{r eval=FALSE, include=FALSE}
colnames(data) |> as.data.frame() |> 
    mutate(new_names = sub("\\?.*", "", `colnames(data)`)) |> 
    distinct(new_names) |> nrow()
```





## Analyse croisée, classification


```{r eval=FALSE, include=FALSE}
suppressPackageStartupMessages({
    library(tidyverse) # data workhorse
    library(correlationfunnel) # rapid exploratory data analysis
    library(cluster) # calculating gower distance and PAM
    library(Rtsne) # dimensionality reduction and visualization
    library(plotly) # interactive graphing
})

set.seed(175) # reproducibility

hr_corr_tbl <- data %>%
    select(8:12, 16:37) %>%
    mutate_all(function(x) gsub("Oui", TRUE, x)) |> 
    mutate_all(function(x) gsub("Non", FALSE, x)) |> 
    binarize(n_bins = 5, thresh_infreq = 0.01, name_infreq = "OTHER", one_hot = TRUE) %>%
    correlate(Attrition__Yes)

hr_corr_tbl %>%
    plot_correlation_funnel() %>%
    ggplotly()
```



```{r eval=FALSE, include=FALSE}
library(dendextend)
dend <- data %>% 
  select(7:10) %>% 
  dist() %>% 
  hclust() %>% 
  as.dendrogram()
 
# Plot
par(mar=c(1,1,1,70))
dend %>%
  set("labels_col", value = c("skyblue", "orange", "grey"), k=30) %>%
  set("branches_k_color", value = c("skyblue", "orange", "grey"), k = 3) %>%
  plot(horiz=TRUE, axes=FALSE)
abline(v = 350, lty = 2)
```


```{r eval=FALSE, include=FALSE}
# Arbre de décision CART
library(rpart)
library(caret)
library(rpart.plot)
# On définit les paramètres de contrôle
ctrl <- rpart.control(minbucket=5, cp=0.01, xval=5, maxdepth=3)

# Fit Theatre
arbre <- rpart(`Quelle est votre catégorie d'emploi actuel ?` ~ ., data = data, method  = "class", control = ctrl)
summary(arbre)
# Plot
rpart.plot(arbre)
X11()
par(xpd=NA)
plot(arbre,uniform=F)
text(arbre,all=T,use.n=T,cex=0.8)
# Voir erreur de prévision selon la taille de l'arbre
plotcp(arbre)
printcp(arbre)
```


# Données issues des entretiens


